Unary prefix operators
Artem-Semenov-dev/CalculatorProject pull request #3
Opened 2022-07-10 14:58 UTC by Artem-Semenov-dev

Now it's really done.

2022-07-12 09:30 UTC, Artem-Semenov-dev commented
Merge reading and updating variables into one machine.

2022-07-21 18:24 UTC, Oleg-Melnik requested changes

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/ScriptElementExecutorFactoryImpl.java
> +                        new ExecutorProgramElementTransducer(ScriptElement.PRODUCE_VARIABLE, this).named("UnaryPrefixOperator"))));
What is PRODUCE_VARIABLE? Why is it named 'UnaryPrefixOperator'? Make it clear.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/executors/NumberExecutor.java
> +
Make it simpler:

        if (executeResult.isPresent()) {

            if (!output.isParseOnly()) {
                output.systemStack().current().pushOperand(executeResult.get());;
            }

            return true;
        }

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/executors/ProcedureFactoryExecutor.java
> +            if (procedureFactory.hasProcedure(functionHolder.getFunctionName())) {
FunctionHolder?)

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/executors/ProcedureFactoryExecutor.java
> +            if (procedureFactory.hasProcedure(functionHolder.getFunctionName())) {
Why is this part of this PR?)

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/executors/RelationalExpressionElementExecutor.java
> +            return false;
What is this?)

            output.memory().clearCache();
            output.memory().updateCache();

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/executors/VariableExecutor.java
> + */
Rewrite.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/program/ProgramMachine.java
> +                    outputChain.memory().updateVariables();
What is this? Provide a name with a sense.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/runtime/Memory.java
>   * {@code Memory} is a class that used to store Double type variables.
Double only?)

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/runtime/Memory.java
> + * Memory has cache that store variables in cases of finite state machine rollback.
Why do you need a cache? Consider removal or provide very clear javadoc.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/util/FunctionTransducer.java
>      private final BiConsumer<O, Value> consumer;
'consumer' of what?

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/util/UnaryPrefixOperatorContext.java
> +        this.scriptContext = scriptContext;
Use Preconditions.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/util/UnaryPrefixOperatorContext.java
> +    private boolean readVariableOnly;
What is this?

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/util/UnaryPrefixOperatorContext.java
> +        this.unaryOperator = unaryOperator;
Use Preconditions.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/util/UnaryPrefixOperatorContext.java
> +        return unaryOperator.apply(operand);
Use Preconditions.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/variable/ProduceVariableTransducer.java
> +    }
Try to make the logic of this method a bit clearer.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/variable/UnaryPrefixOperatorTransducer.java
> +        Optional<UnaryOperator<Value>> unaryOperator = factory.create(inputChain.readOperator());
InputChain can't have method 'readOperator()'.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/variable/UnaryPrefixOperatorTransducer.java
> +            inputChain.incrementPosition();
Why do you need it here? +1? Why? Logic is not clear.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/whileoperator/WhileOperatorContext.java
>      private int position;
Position of what?

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/whileoperator/WhileOperatorContext.java
Condition value?

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/main/java/com/teamdev/bazascript/interpreter/whileoperator/WhileOperatorContext.java
>          this.position = position;
Use Preconditions.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/test/java/com/teamdev/bazascript/interpreter/InterpreterTest.java
>  class InterpreterTest extends AbstractTest {
Separate the test by testing elements.

2022-07-21 18:24 UTC, Oleg-Melnik commented on bazascript/src/test/java/com/teamdev/bazascript/interpreter/UnaryPrefixOperatorTest.java
> +        );
Add more tests and use DOT at the end of sentences.

2022-07-21 18:24 UTC, Oleg-Melnik commented on fsm/src/main/java/com/teamdev/fsm/CharSequenceReader.java
This method can't be here. CharSequenceReader knows nothing about operators.

2022-07-21 18:24 UTC, Oleg-Melnik commented on fsm/src/main/java/com/teamdev/fsm/CharSequenceReader.java
> +
This method can't be here. CharSequenceReader knows nothing about operators.

2022-07-21 18:24 UTC, Oleg-Melnik commented on fsm/src/main/java/com/teamdev/fsm/CharSequenceReader.java
> +        List<Character> operators = List.of('+', '-', '>', '<', '=', '%', '^', '*', '/');
Only factory may know the signs of operators.

2022-07-21 18:24 UTC, Oleg-Melnik commented on implementations/src/main/java/com/teamdev/implementations/machines/expression/ExpressionMachine.java
> +                .withTemporaryState(ExpressionStates.OPERAND)
Why is OPERAND temporary? This breaks my brain.

2022-07-21 18:24 UTC, Oleg-Melnik commented on implementations/src/main/java/com/teamdev/implementations/operators/PrefixUnaryOperatorFactory.java
> +    }
2 of 3 lines of code are the same... Remove code duplication.

2022-07-25 16:28 UTC, merged